[package]
name = "pacvamp-repo"
description = "Server-side tooling for a repository that serves pacvamp clients"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true

[[bin]]
name = "pacvamp-repo"
path = "src/main.rs"

[dependencies]
alpm-db.workspace = true
base64.workspace = true
color-eyre.workspace = true
eyre.workspace = true
jiff.workspace = true
nix = { workspace = true, features = ["fs"] }
pacvamp.workspace = true
pacvamp-cli-support.workspace = true
pacvamp-policy.workspace = true
p256.workspace = true
packslip = { workspace = true, features = ["create"] }
semver.workspace = true
blake2.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tempfile.workspace = true
toml.workspace = true
ureq.workspace = true
usage_rs.workspace = true
