[package]
name = "pacvamp"
description = "A trust-focused package manager for pacman-based Linux distributions"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true

[features]
test-pacman = []

[lib]
name = "pacvamp"
path = "src/lib.rs"

[[bin]]
name = "pacvamp"
path = "src/main.rs"

[[test]]
name = "transactions"
path = "tests/transactions.rs"
required-features = ["test-pacman"]

[dependencies]
alpm-db.workspace = true
base64.workspace = true
color-eyre.workspace = true
eyre.workspace = true
indexmap.workspace = true
jiff.workspace = true
landlock.workspace = true
libc.workspace = true
nix = { workspace = true, features = ["fs"] }
pacvamp-cli-support.workspace = true
pacvamp-policy.workspace = true
packslip.workspace = true
ratatui.workspace = true
seccompiler.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
thiserror.workspace = true
tempfile.workspace = true
tar = "0.4"
toml.workspace = true
toml_edit.workspace = true
ureq.workspace = true
usage_rs.workspace = true
which.workspace = true

[dev-dependencies]
packslip = { workspace = true, features = ["create"] }
insta.workspace = true
serde_json.workspace = true
