[package]
name = "omapac"
description = "The system package manager for Omarchy"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true

[features]
test-pacman = []

[lib]
name = "omapac"
path = "src/lib.rs"

[[bin]]
name = "omapac"
path = "src/main.rs"

[[test]]
name = "transactions"
path = "tests/transactions.rs"
required-features = ["test-pacman"]

[dependencies]
alpm-db.workspace = true
color-eyre.workspace = true
eyre.workspace = true
jiff.workspace = true
nix.workspace = true
omapac-cli-support.workspace = true
omapac-policy.workspace = true
packslip.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
usage_rs.workspace = true
which.workspace = true

[dev-dependencies]
insta.workspace = true
serde_json.workspace = true
tempfile.workspace = true
